# Generated by Django 4.1.7 on 2023-08-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_criacao_url_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urllog',
            name='url_redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='encurtador.urlredirect'),
        ),
    ]
